/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.meia;
// package must be defined in packages from kmodule.xml file

//list any import classes here.
import org.meia.model.Conclusion;
import org.meia.model.Quiz;
import org.meia.model.Question;
import org.meia.model.QuestionCategory;

//declare any global variables here

query "Conclusions"
	$conclusion : Conclusion()
end

rule "r1"
when
    $q : Quiz()
    exists Question(id == 1, answer == "Sim") from $q.getQuizInitial()
    exists Question(id == 2, answer == "Sim") from $q.getQuizInitial()
then
    Conclusion c = new Conclusion(Conclusion.ANXIETY_AS_NORMAL_FACTOR);
        		insert(c);
end

rule "Diagnóstico de  Ansiedade"
when
    $q : Quiz()
    exists Question(id == 3, answer == "Sim") from $q.getQuizInitial()
then
    Conclusion c = new Conclusion(Conclusion.ANXIETY_AS_NORMAL_FACTOR);
    		insert(c);
    System.out.println("Conclusão: "+c);
end


rule "Diagnóstico de  Ansiedade 2"
when
    $q : Quiz()
    $qc : QuestionCategory(category == "transtorno_panico")
    exists Question(id == 1, answer == "Sim") from $q.getQuiz40()
then
    Conclusion c = new Conclusion(Conclusion.PANIC_SYNDROME);
    		insert(c);
    System.out.println("Conclusão: "+c);
end

/*rule "unknown"
	when
		not Conclusion()
	then
		Conclusion c = new Conclusion(Conclusion.UNKNOWN);
		insert(c);
end*/

